version: "3"
services: 
  git:
    build: 
      clone/.
    volumes:
    - /tmp/datavolume/:/source_code/
  customerservice:
    build: 
      customerservicecompilation/.
    volumes: 
      - /tmp/datavolume/Customer/:/source_code/
    depends_on:
      - git
    ports:
      - "82:8080"
  orderservice:
    build: 
      orderservice/.
    volumes: 
      - /tmp/datavolume/Order/:/source_code/
    depends_on:
      - git
    ports:
      - "81:8080"
  node:
    build: 
      node/.
    volumes:
      - /tmp/datavolume/b2ctouresbalon/:/source_code/
    depends_on:
      - git
  mocks:
    build: 
      wiremocks/.
    volumes:
      - /tmp/datavolume/wiremock/:/code/
    depends_on:
      - git
  httpd:
    build: httpd/.
    volumes:
      - /tmp/datavolume/b2ctouresbalon/:/site/
    ports:
      - "83:80"
    links:
      - orderservice
    depends_on:
      - node
