version: "2"
services: 
  git:
    build: clone/.
    volumes:
    - /tmp/datavolume/:/source_code/
  npm:
    build: npm/.
    image: automate-build/npm
    volumes: 
    - /tmp/datavolume/frontend:/source_code/
    depends_on:
    - "git"
  node:
    build: node/.
    volumes:
    - /tmp/datavolume/frontend:/source_code/
    depends_on:
    - "npm"
  #backend:
  #  build: backend/.
  #frontend:
  #  build: frontend/.
  #  depends_on: 
  #  - "compile_front"
#volumes:
  #datavolume: 
