version: "2"
services: 
  git:
    build: clone/.
    volumes:
    - /tmp/datavolume/:/source_code/
  node:
    build: node/.
    volumes:
    - /tmp/datavolume/frontend:/source_code/
    depends_on:
    - git
  httpd:
    build: httpd/.
    volumes:
    - /tmp/datavolume/frontend/:/site/
    ports:
    - "8080:80"
    depends_on:
    - node
