FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y npm
VOLUME /source_code/
#WORKDIR /source_code/frontend
RUN ["echo","******************************************************"]
RUN ["ls","-l"]
RUN ["echo","******************************************************"]
RUN ["ls","-l","/source_code"]
#RUN ["echo","******************************************************"]
#RUN ["npm","install"]
